### ISSUE TITLE
Can I use this to skeleton the Point Cloud data?

### ISSUE THREAD

**Issue by Lixiao-bai** [Frank-ZY-Dou/Coverage_Axis#2]

**Comment by Frank-ZY-Dou** [comment]
Hi~ This repo provides the skeletal point selection code for skeletonization. It could handle the point cloud input; see a demo here: https://github.com/Frank-ZY-Dou/Coverage_Axis/blob/main/README.md#point-cloud-input.

To get the final skeleton output, you could follow the paper to compute a Power Diagram and take it dual graph to connect the points to form a skeleton.
