### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by Lixiao-bai** [Frank-ZY-Dou/Coverage_Axis#3]
I have some problem when I try to use it on Ubuntu because of the missing of matlab and mosek, So I want to try the matlab one, cloud  you tell me some information about the Matlab version?

**Comment by Frank-ZY-Dou** [comment]
Understood. However, I am busy with DDLs. I will upload a full MATLAB version by the end of June.
You could email me your wechat id so that we could talk later.

**Comment by Frank-ZY-Dou** [comment]
> I have some problem when I try to use it on Ubuntu because of the missing of matlab and mosek, So I want to try the matlab one, cloud you tell me some information about the Matlab version?

Hi, the point selection code in MATLAB has been released: https://github.com/Frank-ZY-Dou/Coverage_Axis/blob/main/MATLAB/Pole_Selection_offset.m
