### ISSUE TITLE
how to view inner-point.obj file?

### ISSUE THREAD

**Issue by manaralnaasan** [Frank-ZY-Dou/Coverage_Axis#4]
i have tried to view the inner point object using 3D application but i got like empty image.
could you please help me how to view the .obj file

**Comment by Frank-ZY-Dou** [comment]
Hi~ Thanks for your interest in our work.
To view a .obj file,  you could use [meshlab](https://www.meshlab.net/). You could simply drag the obj file into the software to view it.
