### ISSUE TITLE
how to visualize the connectivity between the inner points? 

### ISSUE THREAD

**Issue by manaralnaasan** [Frank-ZY-Dou/Coverage_Axis#6]
i need to visualize the skeleton that connects the inner points.

**Comment by Frank-ZY-Dou** [comment]
Hi, Currently, this repo only provides the **skeletal point selection** code for skeletonization. To get the final skeleton output, you could follow the paper to compute a Power Diagram and take it dual graph to connect the points to form a skeleton; we will release the code but it may take a bit of time.

**Comment by manaralnaasan** [comment]
Thank you 😊
