### ISSUE TITLE
Connection code

### ISSUE THREAD

**Issue by cv-chaitali** [Frank-ZY-Dou/Coverage_Axis#7]
Hello, I've read the paper and found it very interesting. I am currently implementing the code. The point visualization and result both are great. I wanna ask if you will upload the axis connection code or may be I missed something.

Thank you for uploading the code.

**Comment by ealwen** [comment]
I have also encountered this problem. Do you have a good plan? The author seems to have used Q-MAT or RDT (Restricted Delaney Triangulation), but I haven't tried it

**Comment by Frank-ZY-Dou** [comment]
Dear all,

Please check them out here: https://github.com/Frank-ZY-Dou/Coverage_Axis/tree/main/skel_connection
The codes are released as they are.

**Comment by Frank-ZY-Dou** [comment]
> I have also encountered this problem. Do you have a good plan? The author seems to have used Q-MAT or RDT (Restricted Delaney Triangulation), but I haven't tried it

Just to clarify, we are using RT (regular triangulation) rather than RDT.
