### ISSUE TITLE
hyperparameter settings

### ISSUE THREAD

**Issue by kiwiiiiMatrix** [Frank-ZY-Dou/Coverage_Axis#8]
The skeleton extraction using Coverage Axis++ for ants works very well, but the results are not satisfactory when I switch to the car in MN40 dataset . Is there a problem with my hyperparameter settings?
![WX20240713-235435@2x](https://github.com/user-attachments/assets/280fd852-7066-4aae-a3e3-d7daea565439)

**Comment by Frank-ZY-Dou** [comment]
Thank you for your interest in our work! Before running the coverage axis, there are a few preliminary steps you need to take. Firstly, ensure your model is normalized according to the settings described in our paper. Additionally, check the medial balls. Based on the figure you provided, it appears that the original medial balls are not well computed. If these balls are not correctly computed with respect to the underlying surface, the dilation process will be significantly affected, leading to suboptimal final results. Therefore, accurate computation of the original medial balls' radius is crucial.

**Comment by kiwiiiiMatrix** [comment]
After Normalized，I got a nice cup，thanks a lot！
<img width="764" alt="image" src="https://github.com/user-attachments/assets/69f10c76-6721-4b1f-850e-7f46ae764633">
