### ISSUE TITLE
How to skeletonize the points cloud input?

### ISSUE THREAD

**Issue by wusar** [Frank-ZY-Dou/Coverage_Axis#9]
First of all, I would like to say that I'm really impressed with your work—it's fantastic! I encountered an issue while trying to skeletonize my point cloud data.

I was attempting to perform skeletonization on a point cloud using your provided cpp tutorial code.
https://github.com/Frank-ZY-Dou/libigl_CA/blob/48dde368218ba9ced5a2a25eeb8fdeb1d7a5ae73/tutorial/FastWindingNumber_CA/main.cpp#L49
 However, I noticed that the code seems to only accept a 3D mesh as input, and it converts the mesh into a surface point cloud and an internal sampled point cloud.

My input model is a pure point cloud in the shape of (point_cloud, 3), not a mesh. In this case, how should I proceed? Is there a recommended method to convert my point cloud into a suitable format for skeletonization?

Thanks for your help!

**Comment by Frank-ZY-Dou** [comment]
Hi Lifan,

I'm glad to hear that, and thanks!

The code I provided is just a demo. To apply FastWinderNumber to point clouds, you can follow the instructions on this website: https://www.dgp.toronto.edu/projects/fast-winding-numbers/

You can also find the source code for Soups and Clouds here: [igl::fast_winding_number](https://github.com/libigl/libigl).

Best regards,
Frank

**Comment by Frank-ZY-Dou** [comment]
Hi, I have added more instructions for this part: https://github.com/Frank-ZY-Dou/Coverage_Axis?tab=readme-ov-file#point-cloud-input
